site_name: Sidekick EPICS Documentation

nav:
    - 'sidekick-overview.md'
    - 'sidekick-motivation.md'
    - 'sidekick-analogies.md'
    - Model 1:
        - 'model1/model1-architecture.md'
        - 'model1/model1-process-variables.md'
        - Client Demos (Python):
            - 'model1/demos/HelloSidekick.ipynb'
            - 'model1/demos/OpenLoop.ipynb'
            - 'model1/demos/OpenLoopBrightness.ipynb'
            - 'model1/demos/OpenLoopHRR.ipynb'
            - 'model1/demos/ClosedLoopBasics.ipynb'
        - Building from Scratch:
            - Source Code/CAD: 'model1/model1-source-components.md'
            - Flash Your Raspberry Pi: 'model1/pi-flash.md'
            - First Boot: 'model1/pi-first-boot.md'
            - Install EPICS v7: 'model1/pi-epics-install.md'
            - Install StreamDevice: 'model1/pi-stream-device-install.md'
            - Install and Configure systemd-ioc: 'model1/pi-systemd-softioc-setup.md'
            - 'model1/pi-systemd-softioc-sidekick.md'
    - Model 3:
        - 'model3/model3-architecture.md'
        - 'model3/model3-process-variables.md'
        - 'model3/model3-hardware-triggers.md'
        - 'model3/model3-ioc-administration.md'
        - Building from Scratch:
            - Source Code/CAD: 'model3/model3-source-components.md'
            - 'model3/model3-flash-teensy.md'
    - Clients:
        - Python Client: 'epics_on_windows_via_anaconda.md'
        - Graphical Client: 'css-phoebus-install-windows.md'
    - 'about.md'
    
#    - Getting Set Up for EPICS in Python:
#        - 'epics_message_single_computer.md'

plugins:
    - mkdocs-jupyter # https://github.com/danielfrg/mkdocs-jupyter
    - mkdocs-video # https://pypi.org/project/mkdocs-video/  (pip install mkdocs-video)

extra_css:
    - css/extra.css
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
#  - https://unpkg.com/mermaid/dist/mermaid.min.js
  
markdown_extensions:
    - toc:
        title: 
        permalink: True
        toc_depth: 2
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.arithmatex # Note: requires extra_javascript above
    - codehilite
    - footnotes

theme:
  name: 'material'
     
copyright: Copyright &copy; 2024 <a href="https://www.scottfeister.com">Scott Feister</a>
