site_name: Sidekick EPICS Documentation

nav:
    - Sidekick Overview: 'sidekick-overview.md'
    - Sidekick Analogies: 'sidekick-analogies.md'
    - Getting Started on Raspberry Pi:
        - Flash Your Raspberry Pi: 'pi-flash.md'
        - First Boot: 'pi-first-boot.md'
        - Install EPICS v7: 'pi-epics-install.md'
        - Install StreamDevice: 'pi-stream-device-install.md'
        - Install and Configure systemd-ioc: 'pi-systemd-softioc-setup.md'
    - EPICS on Your Laptop via Python:
        - 'epics_on_windows_via_anaconda.md'
        - 'epics_message_single_computer.md'
    - 'about.md'
    

extra_css:
    - css/extra.css
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
#  - https://unpkg.com/mermaid/dist/mermaid.min.js
  
markdown_extensions:
    - toc:
        title: 
        permalink: True
        toc_depth: 2
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.arithmatex # Note: requires extra_javascript above
    - codehilite
    - footnotes

theme:
  name: 'material'
     
copyright: Copyright &copy; 2022 <a href="http://www.scottfeister.com">Scott Feister</a>
