site_name: Sidekick EPICS Documentation

nav:
    - 'sidekick-overview.md'
    - 'sidekick-motivation.md'
    - 'sidekick-analogies.md'
    - General Setup:
        - Python Client Setup: 'epics_on_windows_via_anaconda.md'
        - Control Panel Setup: 'css-phoebus-install-windows.md'    
    - Model 1:
        - 'model1/model1-architecture.md'
        - 'model1/model1-command-list.md'
        - 'model1/model1-source-components.md'
        - Configure Raspberry Pis:
            - Flash Your Raspberry Pi: 'model1/pi-flash.md'
            - First Boot: 'model1/pi-first-boot.md'
            - Install EPICS v7: 'model1/pi-epics-install.md'
            - Install StreamDevice: 'model1/pi-stream-device-install.md'
            - Install and Configure systemd-ioc: 'model1/pi-systemd-softioc-setup.md'
            - 'model1/pi-systemd-softioc-sidekick.md'
        - Python Demos:
            - 'model1/demos/HelloSidekick.ipynb'
            - 'model1/demos/OpenLoop.ipynb'
            - 'model1/demos/OpenLoopBrightness.ipynb'
            - 'model1/demos/OpenLoopHRR.ipynb'
            - 'model1/demos/ClosedLoopBasics.ipynb'
    - Model 3:
        - 'model3/model3-architecture.md'
        - 'model3/model3-hardware-triggers.md'
        - 'model3/model3-pv-list.md'
#    - Getting Set Up for EPICS in Python:
#        - 'epics_message_single_computer.md'
    - 'about.md'
    

plugins:
    - mkdocs-jupyter # https://github.com/danielfrg/mkdocs-jupyter

extra_css:
    - css/extra.css
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
#  - https://unpkg.com/mermaid/dist/mermaid.min.js
  
markdown_extensions:
    - toc:
        title: 
        permalink: True
        toc_depth: 2
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.arithmatex # Note: requires extra_javascript above
    - codehilite
    - footnotes

theme:
  name: 'material'
     
copyright: Copyright &copy; 2024 <a href="https://www.scottfeister.com">Scott Feister</a>
